---
name: lineage_scan

on:
  schedule:
    - cron: "15 * * * *"
  workflow_dispatch:

env:
  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

jobs:
  khulnasoft-lab:
    runs-on: ubuntu-latest
    steps:
      - name: Check all organization repositories
        uses: khulnasoft-lab/action-lineage@develop
        with:
          access_token: ${{ env.ACCESS_TOKEN }}
          repo_query: "org:khulnasoft-lab archived:false"
